const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94764038550"
const SESSION_ID = "PRABATH-MD~0uMA2LBY#f9huClKwkg3oXVzuTD-WrY_g4wbahS3pGAttZZlV_VU"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
